/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique;

import BaseDD.Connex;
import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author linda
 */
public class CategorieProd extends javax.swing.JPanel {

    Connex c = new Connex();

    /**
     * Creates new form Produit
     */
    public CategorieProd() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimEcran = tk.getScreenSize();
        int largeur = dimEcran.width - 40;
        int hauteur = dimEcran.height - 40;
        this.setSize(largeur, hauteur);
        verifierCategorieProduit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        effacer = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        gauche = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablecategorie = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("DESCRIPTION :");

        jLabel1.setText("NOM CATEGORIE :");

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        jScrollPane1.setViewportView(txtdescription);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        effacer.setText("EFFACER");
        effacer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });

        ajouter.setText("VALIDER");
        ajouter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        bmodifier.setText("MODIFIER");
        bmodifier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(effacer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(effacer, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(bmodifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gauche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2leftarrow.png"))); // NOI18N
        gauche.setFocusable(false);
        gauche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gauche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaucheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gauche, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(gauche)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        tablecategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecategorieMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablecategorie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        ajouter();
    }//GEN-LAST:event_ajouterActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        // TODO add your handling code here:
        txtnom.setText(null);
        txtdescription.setText(null);
    }//GEN-LAST:event_effacerActionPerformed

    private void gaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaucheActionPerformed
        // TODO add your handling code here:
        NewJFrame3.pile.show(NewJFrame3.pancard, "gestion");
    }//GEN-LAST:event_gaucheActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        // TODO add your handling code here:
        modifier();
    }//GEN-LAST:event_bmodifierActionPerformed

    private void tablecategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecategorieMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1) {
            this.selectionnerLigne();
        }
    }//GEN-LAST:event_tablecategorieMouseClicked
    public final void verifierCategorieProduit() {
        String requette = "select * from categorie_produit";
        String[] entete = {"Code de catégorie", "Nom de catégorie", "Description"};
        Connex.select(requette);
        c.tableau(requette, tablecategorie, entete);
    }
    public int selectionnerLigne() {
        boolean flag;
        int ligne = tablecategorie.getSelectedRow();
        if (ligne == -1) {
            JOptionPane.showMessageDialog(null, "Vous n'avez pas selectionné de ligne dans la table");
            flag = false;
            return ligne;
        } else {
            String nom = tablecategorie.getValueAt(ligne, 1).toString();
            txtnom.setText(nom);
            String des = tablecategorie.getValueAt(ligne, 2).toString();
            txtdescription.setText(des);
            flag = true;
            return ligne;

        }
    }
    public void ajouter() {
        String var = "insert into categorie_produit (nom_categorie ,description)"
                + "values('" + this.txtnom.getText() + "'" + "," + "'" + this.txtdescription.getText() + "');";
        String var2 = "select * from categorie_produit";
        String[] entete = {"Code de catégorie", "Nom de catégorie", "Description"};
        //System.out.println(var);
        Connex.update(var);
        c.tableau(var2, tablecategorie, entete);
    }
    public void modifier() {
        boolean flag = true;
        if (flag) {
            int g = tablecategorie.getSelectedRow();
            int p = Integer.parseInt(tablecategorie.getValueAt(g, 0).toString());
            String nom = tablecategorie.getValueAt(p, 1).toString();
            String description = tablecategorie.getValueAt(p, 2).toString();
            String req = "update categorie_produit set nom_categorie = '" + nom + "', description = '" + description + "' "
                    + "where code_categorie = " + p + ";";
            Connex.update(req);
            String requette = "select * from categorie_produit";
            String[] entete = {"Code de catégorie", "Nom de catégorie", "Description"};
            c.tableau(requette, tablecategorie, entete);
            JOptionPane.showMessageDialog(null, "La modification a réussit !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de modification !!!");

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton effacer;
    private javax.swing.JButton gauche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablecategorie;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
