/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique;

import BaseDD.Connex;
import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToolBar;

/**
 *
 * @author linda
 */
public class Client extends javax.swing.JPanel {
     Connex c = new Connex();
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimEcran = tk.getScreenSize();
        int largeur = dimEcran.width - 40;
        int hauteur = dimEcran.height - 40;
        this.setSize(largeur, hauteur);
        verifierClients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        nom = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        addresse = new javax.swing.JLabel();
        txtaddresse = new javax.swing.JTextField();
        ville = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtville = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        valider = new javax.swing.JButton();
        effacer = new javax.swing.JButton();
        bsupprimer = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableclient = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        bguauche = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));

        nom.setText("NOM :");

        addresse.setText("ADDRESSE :");

        ville.setText("VILLE :");

        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });

        tel.setText("TELEPHONE :");

        mail.setText("E-MAIL :");

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        valider.setText("VALIDER");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        valider.setBounds(30, 10, 92, 30);
        jLayeredPane3.add(valider, javax.swing.JLayeredPane.DEFAULT_LAYER);

        effacer.setText("Effacer");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });
        effacer.setBounds(120, 10, 67, 30);
        jLayeredPane3.add(effacer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bsupprimer.setText("SUPPRIMER");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });
        bsupprimer.setBounds(220, 10, 89, 30);
        jLayeredPane3.add(bsupprimer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bmodifier.setText("MODIFIER");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });
        bmodifier.setBounds(330, 10, 115, 30);
        jLayeredPane3.add(bmodifier, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tableclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableclientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableclient);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 333, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bguauche.setBackground(new java.awt.Color(0, 51, 255));
        bguauche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2leftarrow.png"))); // NOI18N
        bguauche.setToolTipText("Retour sur la page d'acceuil");
        bguauche.setFocusable(false);
        bguauche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bguauche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bguauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguaucheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bguauche, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom)
                    .addComponent(mail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ville)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addresse)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtaddresse, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(txtville))))
                .addGap(30, 30, 30)
                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bguauche))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addresse))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mail)
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ville)
                            .addComponent(txtville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed

        ajouter();
    }//GEN-LAST:event_validerActionPerformed

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        // TODO add your handling code here:
        String reqette = "select * from clients";
        String[] entete = {"Numero", "Addresse", "Telephone", "E-mail", "Nom", "Ville"};
        int g = tableclient.getSelectedRow();
        int p = Integer.parseInt(tableclient.getValueAt(g, 0).toString());
        int reponse = JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer ce client ?");
        if (reponse == 0) {
            String requete = "delete from clients where code_client=" + p + "";
            Connex.update(requete);
            c.tableau(reqette, tableclient, entete);
            JOptionPane.showMessageDialog(null, "Suppression OK !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de suppression");
        }


    }//GEN-LAST:event_bsupprimerActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        // TODO add your handling code here:
        txtnom.setText(null);
        txtaddresse.setText(null);
        txtville.setText(null);
        txtmail.setText(null);
        txttel.setText(null);
    }//GEN-LAST:event_effacerActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        // TODO add your handling code here:
       modifier();
    }//GEN-LAST:event_bmodifierActionPerformed

    private void bguaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguaucheActionPerformed
        // TODO add your handling code here:
        NewJFrame3.pile.show(NewJFrame3.pancard, "gestion");
    }//GEN-LAST:event_bguaucheActionPerformed

    private void tableclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableclientMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1) {
            this.selectionligne();
        }
    }//GEN-LAST:event_tableclientMouseClicked

    public int selectionligne() {
        boolean flag;
        int ligne = tableclient.getSelectedRow();
        if (ligne == -1) {
            JOptionPane.showMessageDialog(null, "Vous n'avez pas selectionné de ligne dans la table");
            flag = false;
            return ligne;
        } else {
            int g = tableclient.getSelectedRow();
            int p = Integer.parseInt(tableclient.getValueAt(g, 0).toString());
            String addr = tableclient.getValueAt(ligne, 1).toString();
            txtaddresse.setText(addr);
            String tel = tableclient.getValueAt(ligne, 2).toString();
            txttel.setText(tel);
            String mail = tableclient.getValueAt(ligne, 3).toString();
            txtmail.setText(mail);
            String nom = tableclient.getValueAt(ligne, 4).toString();
            txtnom.setText(nom);
            String ville = tableclient.getValueAt(ligne, 5).toString();
            txtville.setText(ville);
            flag = true;
            return ligne;
        }
    }
    public final void verifierClients() {
        String reqette = "select * from clients";
        String[] entete = {"Numero", "Addresse", "Telephone", "E-mail", "Nom", "Ville"};
        c.tableau(reqette, tableclient, entete);
    }
    public void modifier() {
         boolean flag = true;
        if (flag) {
            int g = tableclient.getSelectedRow();
            int p = Integer.parseInt(tableclient.getValueAt(g, 0).toString());
            String addr = txtaddresse.getText();
            String tel = txttel.getText().toString();
            String mail = txtmail.getText();
            String nom = txtnom.getText();
            String ville = txtville.getText().toString();
            //String notes = txtnotes.getText().toString();
            String requete = "update clients set addresse='" + addr + "',num_tel = '" + tel
                    + "',e_mail='" + mail + "'"
                    + ",nom_client='" + nom + "',ville='" + ville + "' where code_client=" + p + ";";
            Connex.update(requete);
            String reqette = "select * from clients";
            String[] entete = {"Numero", "Addresse", "Telephone", "E-mail", "Nom", "Ville"};
            c.tableau(reqette, tableclient, entete);
            JOptionPane.showMessageDialog(null, "La modification a réussit !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de modification !!!");

        }
    }
    public void ajouter() {
        boolean flag = true;
        if (flag) {
            String var = "insert into clients (e_mail , addresse , ville , num_tel , nom_client )"
                    + "values('" + this.txtmail.getText() + "'" + "," + "'" + this.txtaddresse.getText() + "'"
                    + "," + "'" + this.txtville.getText() + "'" + "," + "'" + this.txttel.getText() + "'" + "," + "'" + this.txtnom.getText() + "');";
            //System.out.println(var);
            Connex.update(var);
            String reqette = "select * from clients";
            String[] entete = {"Numero", "Addresse", "Telephone", "E-mail", "Nom", "Ville"};
            c.tableau(reqette, tableclient, entete);
            JOptionPane.showMessageDialog(null, "L'jout a réussit !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec d'ajout !!!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresse;
    private javax.swing.JButton bguauche;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JButton effacer;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel nom;
    private javax.swing.JTable tableclient;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField txtaddresse;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtville;
    private javax.swing.JButton valider;
    private javax.swing.JLabel ville;
    // End of variables declaration//GEN-END:variables
}
