/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique;

import BaseDD.Connex;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author linda
 */
public final class Employe extends javax.swing.JPanel {
Connex c = new Connex();
static ResultSet result = null;
    /**
     * Creates new form Employe
     *
     */
    public Employe() {
        initComponents();
        this.setSize(1326, 618);
        jTabbedPane1.setSize(1166, 618);
        jPanel1.setSize(1166, 618);
        tablemploye.setSize(1000, 600);
        afficherListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        date_embauche = new com.toedter.calendar.JDateChooser();
        txtlogin = new javax.swing.JTextField();
        txtnum_tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnom_employe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtaddresse = new javax.swing.JTextField();
        date_naiss = new com.toedter.calendar.JDateChooser();
        txtprenom_employe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        effacer = new javax.swing.JButton();
        bvalider = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        bsupprimer = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chercher = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chemin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemploye = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        guauche = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("TELEPHONE :");

        jLabel4.setText("DATE DE NAISSANCE :");

        jLabel1.setText("NOM :");

        jLabel5.setText("DATE D'EMBAUCHE :");

        jLabel3.setText("ADDRESSE :");

        txtaddresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddresseActionPerformed(evt);
            }
        });

        jLabel2.setText("PRENOM :");

        jLabel9.setText("LOGIN :");

        jLabel10.setText("PASSWORD :");

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        effacer.setText("EFFACER");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });

        bvalider.setText("AJOUTER");
        bvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvaliderActionPerformed(evt);
            }
        });

        bmodifier.setText("MODIFIER");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });

        bsupprimer.setText("SUPPRIMER");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(effacer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bmodifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bsupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(effacer)
                    .addComponent(bvalider)
                    .addComponent(bmodifier)
                    .addComponent(bsupprimer))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(121, 121, 121)
                                        .addComponent(txtnom_employe, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date_naiss, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel9))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(txtprenom_employe, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(date_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddresse, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnum_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom_employe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtprenom_employe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(date_naiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(date_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtaddresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtnum_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PHOTO");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        chercher.setText("...");
        chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherActionPerformed(evt);
            }
        });

        jLabel11.setText("Chercher:");

        jLabel12.setText("Chemin:");

        chemin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablemploye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemployeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemploye);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        guauche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2leftarrow.png"))); // NOI18N
        guauche.setFocusable(false);
        guauche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guauche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guaucheActionPerformed(evt);
            }
        });
        jToolBar1.add(guauche);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addComponent(chercher))))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chemin, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chercher)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chemin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AJOUTER ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        // TODO add your handling code here:
        txtnom_employe.setText(null);
        txtprenom_employe.setText(null);
        txtaddresse.setText(null);
        txtnum_tel.setText(null);
        txtlogin.setText(null);
        txtpassword.setText(null);


    }//GEN-LAST:event_effacerActionPerformed

    private void bvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvaliderActionPerformed
        // TODO add your handling code here:
        ajouter();
    }//GEN-LAST:event_bvaliderActionPerformed

    private void txtaddresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddresseActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        // TODO add your handling code here:
        modifier();
    }//GEN-LAST:event_bmodifierActionPerformed

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        // TODO add your handling code here:
       supprimer();
    }//GEN-LAST:event_bsupprimerActionPerformed

    private void chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showDialog(this, "Ajouter");
        String lien;
        if (chooser.getApproveButtonText().equals("Ajouter")) {
            lien = chooser.getSelectedFile().getAbsolutePath().toString();
            chemin.setText(lien);
            photo.setIcon(new javax.swing.ImageIcon(lien));
            lien2 = lien.replace('\\', '_');
        }
    }//GEN-LAST:event_chercherActionPerformed

    private void guaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guaucheActionPerformed
        // TODO add your handling code here:
        NewJFrame3.pile.show(NewJFrame3.pancard, "gestion");
    }//GEN-LAST:event_guaucheActionPerformed

    private void tablemployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemployeMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1) {
            this.selectionEmploye();
        }
    }//GEN-LAST:event_tablemployeMouseClicked

    public int selectionEmploye() {
        boolean flag;
        int ligne = tablemploye.getSelectedRow();
        if (ligne == -1) {
            JOptionPane.showMessageDialog(null, "Vous n'avez pas selectionné de ligne dans la table");
            flag = false;
            return ligne;
        } else {
            String bnom = tablemploye.getValueAt(ligne, 1).toString();
            txtnom_employe.setText(bnom);
            String bprenom = tablemploye.getValueAt(ligne, 2).toString();
            txtprenom_employe.setText(bprenom);
            String badresse = tablemploye.getValueAt(ligne, 5).toString();
            txtaddresse.setText(badresse);
            String btel = tablemploye.getValueAt(ligne, 6).toString();
            txtnum_tel.setText(btel);
            String blogin = tablemploye.getValueAt(ligne, 7).toString();
            txtlogin.setText(blogin);
            String bpass = tablemploye.getValueAt(ligne, 8).toString();
            txtpassword.setText(bpass);
            String num = String.valueOf(tablemploye.getValueAt(ligne, 0));
            int numero = Integer.valueOf(num);
            chemin1 = "select photo from employe where num_employe = "+numero+";";
            mettrePhoto(chemin1);
            flag = true;
            return ligne;

        }
    }
    public void mettrePhoto(String req) {
        result = Connex.select(req);
            try {
                while(result.next()) {
                    lien4 = result.getString(1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
            }
            lien3 = lien4.replace('_', '\\');
            chemin.setText(lien3);
            photo.setIcon(new javax.swing.ImageIcon(lien3));
    }
    String lien2 , lien3,lien4 , chemin1;
    public void afficherListe() {
        String reqette = "select num_employe , nom_employe,"
                + "prenom_employe,date_naiss,date_embauche,addresse,num_tel,login,password from employe;";
        String[] entete = {"Numero", "Nom",
            "Prénom", "Date de naissance", "Date d'embauche", "Addresse", "Telephone", "Login", "Password"};
        c.tableau(reqette, tablemploye, entete);
    }
    public void ajouter() {
        boolean flag = true;
        if (flag) {
            String date0 = this.date_naiss.getCalendar().get(Calendar.YEAR) + "-"
                    + (1 + this.date_naiss.getCalendar().get(Calendar.MONTH)) + "-"
                    + this.date_naiss.getCalendar().get(Calendar.DAY_OF_MONTH);
            String date1 = this.date_embauche.getCalendar().get(Calendar.YEAR) + "-"
                    + (1 + this.date_embauche.getCalendar().get(Calendar.MONTH)) + "-"
                    + this.date_embauche.getCalendar().get(Calendar.DAY_OF_MONTH);

            String var = "insert into employe (nom_employe , prenom_employe , addresse ,"
                    + " date_naiss , date_embauche , num_tel , login , password ,photo)"
                    + "values('" + this.txtnom_employe.getText() + "'" + "," + "'" + this.txtprenom_employe.getText() + "'"
                    + "," + "'" + this.txtaddresse.getText() + "'" + "," + "'" + date0 + "'" + "," + "'"
                    + date1 + "'" + "," + "'" + this.txtnum_tel.getText() + "'" + "," + "'" + this.txtlogin.getText()
                    + "'" + "," + "'" + this.txtpassword.getText() + "'"+","+"'"+lien2+"');";
            //System.out.println(var);
            Connex.update(var);
            String reqette = "select num_employe , nom_employe,"
                    + "prenom_employe,date_naiss,date_embauche,addresse,num_tel,login,password from employe;";
            String[] entete = {"Numero", "Nom",
                "Prénom", "Date de naissance", "Date d'embauche", "Addresse", "Telephone", "Login", "Password"};
            c.tableau(reqette, tablemploye, entete);
            JOptionPane.showMessageDialog(null, "L'jout a réussit !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec d'ajout !!!");
        }
    }
    public void modifier() {
         boolean flag = true;
        if (flag) {
            int g = tablemploye.getSelectedRow();
            int p = Integer.parseInt(tablemploye.getValueAt(g, 0).toString());
            String bnom = txtnom_employe.getText();
            String bprenom = txtprenom_employe.getText();
            String date0 = this.date_naiss.getCalendar().get(Calendar.YEAR) + "-"
                    + (1 + this.date_naiss.getCalendar().get(Calendar.MONTH)) + "-"
                    + this.date_naiss.getCalendar().get(Calendar.DAY_OF_MONTH);
            String date1 = this.date_embauche.getCalendar().get(Calendar.YEAR) + "-"
                    + (1 + this.date_embauche.getCalendar().get(Calendar.MONTH)) + "-"
                    + this.date_embauche.getCalendar().get(Calendar.DAY_OF_MONTH);
            String badresse = txtaddresse.getText();
            String log = txtlogin.getText().toString();
            String pass = txtpassword.getText().toString();
            String lien5 = chemin.getText();
            String lien6 = lien5.replace('\\', '_');
            int tel = Integer.parseInt(txtnum_tel.getText().toString());
            String requete = "update employe set nom_employe='" + bnom + "',prenom_employe = '" + bprenom
                    + "',addresse='" + badresse + "'"
                    + ",login='" + log + "',password='" + pass + "',num_tel='" + tel
                    + "',date_naiss='" + date0 + "', date_embauche = '" + date1 + "', photo = '"+lien6+"' where num_employe=" + p + ";";
            Connex.update(requete);
            String lien7 = "select photo from employe where num_employe=" + p + ";";
            mettrePhoto(lien7);
            String reqette = "select num_employe , nom_employe,"
                    + "prenom_employe,date_naiss,date_embauche,addresse,num_tel,login,password from employe;";
            String[] entete = {"Numero", "Nom",
                "Prénom", "Date de naissance", "Date d'embauche", "Addresse", "Telephone", "Login", "Password"};
            c.tableau(reqette, tablemploye, entete);
            JOptionPane.showMessageDialog(null, "La modification a réussit !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de modification !!!");

        }
    }
    public void supprimer() {
         String req = "select num_employe , nom_employe,"
                + "prenom_employe,date_naiss,date_embauche,addresse,num_tel,login,password from employe;";
        String[] entete = {"Numero", "Nom",
            "Prénom", "Date de naissance", "Date d'embauche", "Addresse", "Telephone", "Login", "Password"};
        int g = tablemploye.getSelectedRow();
        int p = Integer.parseInt(tablemploye.getValueAt(g, 0).toString());
        int reponse = JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer cet employé ?");
        if (reponse == 0) {
            String requete = "delete from employe where num_employe=" + p + "";
            Connex.update(requete);
            c.tableau(req, tablemploye, entete);
            JOptionPane.showMessageDialog(null, "Suppression OK !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de suppression");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JButton bvalider;
    private javax.swing.JLabel chemin;
    private javax.swing.JButton chercher;
    private com.toedter.calendar.JDateChooser date_embauche;
    private com.toedter.calendar.JDateChooser date_naiss;
    private javax.swing.JButton effacer;
    private javax.swing.JButton guauche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel photo;
    private javax.swing.JTable tablemploye;
    private javax.swing.JTextField txtaddresse;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnom_employe;
    private javax.swing.JTextField txtnum_tel;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtprenom_employe;
    // End of variables declaration//GEN-END:variables
}
