/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author linda
 */
public class NewJFrame3 extends javax.swing.JFrame {

    public static JPanel pancard = new JPanel();
    public static CardLayout pile = new CardLayout();
    CategorieProd ca = new CategorieProd();
    Client cli = new Client();
    Employe e = new Employe();
    Fournisseur f = new Fournisseur();
    Produit p = new Produit();
    Vendre ve = new Vendre();
    Gestions g = new Gestions();
    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
        int x,y;
        setTitle("Acceuil");
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimEcran = tk.getScreenSize();
        int largeur = dimEcran.width - 40;
        int hauteur = dimEcran.height - 40;
        this.setSize(largeur, hauteur);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
 
        pancard.setLayout(pile);
        pancard.add(g, "gestion");
//        pile.show(pancard, "gestion");
        pancard.add(ca, "categorie");
        pancard.add(cli, "clients");
        pancard.add(e, "employe");
        pancard.add(f, "fournisseur");
        pancard.add(p, "produit");
        pancard.add(ve, "ventes");
        this.setContentPane(pancard);
        

    }

    //2eme constructeur
    public NewJFrame3(int t) {
        initComponents();
        Gestions.bempl.setEnabled(false);
        int x,y;
        setTitle("Acceuil");
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimEcran = tk.getScreenSize();
        int largeur = dimEcran.width - 40;
        int hauteur = dimEcran.height - 40;
        this.setSize(largeur, hauteur);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
 
        pancard.setLayout(pile);
        pancard.add(g, "gestion");
//        pile.show(pancard, "gestion");
        pancard.add(ca, "categorie");
        pancard.add(cli, "clients");
        pancard.add(e, "employe");
        pancard.add(f, "fournisseur");
        pancard.add(p, "produit");
        pancard.add(ve, "ventes");
        this.setContentPane(pancard);
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
