/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutique;

import BaseDD.Connex;
import JtableVente.Vente;
import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author linda
 */
public class Produit extends javax.swing.JPanel {
    Connex c = new Connex();
    
    /**
     * Creates new form Produit
     */
    public Produit() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimEcran = tk.getScreenSize();
        int largeur = dimEcran.width - 40;
        int hauteur = dimEcran.height - 40;
        this.setSize(largeur, hauteur);

        String[] entete = {"Reference du produit", "Code de catégorie", "Fournisseur N°", 
                "Prix unitaire","Unité", "Quantité de produit par unité", "Désignation"};
        String reqette = "select reference_produit, code_categorie,code_fournisseur,"
                + "prix_unitaire_produit,unite,quantite_par_unite,designation from produit;";
        Connex.select(reqette);
        c.tableau(reqette, tableproduit, entete);
      
        String req = "select code_categorie from categorie_produit order by nom_categorie;";
        c.combobox(req, combo2);
        String reque = "select code_fournisseur from fournisseur;";
        c.combobox(reque, comboFour);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtpu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtquantite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdesignation = new javax.swing.JTextField();
        bannuler = new javax.swing.JPanel();
        bajouter = new javax.swing.JButton();
        bannul = new javax.swing.JButton();
        bmodifier = new javax.swing.JButton();
        bsupprimer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comboFour = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        unite = new javax.swing.JTextField();
        guauche = new javax.swing.JButton();
        rechercher = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableproduit = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("CODE CATEGORIE :");

        jLabel2.setText("PRIX UNITAIRE :");

        jLabel4.setText("QUANTITE :");

        jLabel5.setText("Désignation :");

        bannuler.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bajouter.setText("Ajouter");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });

        bannul.setText("Annuler");
        bannul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulActionPerformed(evt);
            }
        });

        bmodifier.setText("Modifier");
        bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodifierActionPerformed(evt);
            }
        });

        bsupprimer.setText("Supprimer");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bannulerLayout = new javax.swing.GroupLayout(bannuler);
        bannuler.setLayout(bannulerLayout);
        bannulerLayout.setHorizontalGroup(
            bannulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannulerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bannul, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bsupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bannulerLayout.setVerticalGroup(
            bannulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannulerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bajouter)
                    .addComponent(bannul)
                    .addComponent(bmodifier)
                    .addComponent(bsupprimer))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel7.setText("CODE  FOURNISSEUR :");

        jLabel6.setText("UNITE :");

        guauche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/2leftarrow.png"))); // NOI18N
        guauche.setFocusable(false);
        guauche.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guauche.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guaucheActionPerformed(evt);
            }
        });

        rechercher.setFont(new java.awt.Font("Maiandra GD", 2, 14)); // NOI18N
        rechercher.setForeground(new java.awt.Color(153, 153, 153));
        rechercher.setText("Recherche selon designation");
        rechercher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        rechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercherMouseClicked(evt);
            }
        });
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercherKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unite, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guauche, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addComponent(comboFour, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(txtpu, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bannuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guauche, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(rechercher))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(txtpu)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(bannuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtquantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(unite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        tableproduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproduit);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
        // TODO add your handling code here:
        ajouter();
    }//GEN-LAST:event_bajouterActionPerformed

    private void bannulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulActionPerformed
        // TODO add your handling code here:
        txtpu.setText(null);
        txtquantite.setText(null);
        txtdesignation.setText(null);
    }//GEN-LAST:event_bannulActionPerformed

    private void bmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodifierActionPerformed
        // TODO add your handling code here:
        modifier();
       
    }//GEN-LAST:event_bmodifierActionPerformed

    private void tableproduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproduitMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.selectionligne();
        }

    }//GEN-LAST:event_tableproduitMouseClicked

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        // TODO add your handling code here:
       supprimer();
    }//GEN-LAST:event_bsupprimerActionPerformed

    private void guaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guaucheActionPerformed
        // TODO add your handling code here:
        NewJFrame3.pile.show(NewJFrame3.pancard, "gestion");
    }//GEN-LAST:event_guaucheActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rechercherActionPerformed

    private void rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercherKeyReleased
        // TODO add your handling code here:
       rechercher();  
    }//GEN-LAST:event_rechercherKeyReleased

    private void rechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercherMouseClicked
        // TODO add your handling code here:
        rechercher.setText("");
        Font police = new Font("Maiandra GD", Font.BOLD, 14);
        rechercher.setFont(police);
        rechercher.setForeground(Color.black);
    }//GEN-LAST:event_rechercherMouseClicked

    public int selectionligne() {
        boolean flag;
        int ligne = tableproduit.getSelectedRow();
        if (ligne == -1) {
            JOptionPane.showMessageDialog(null, "Vous n'avez pas selectionné de ligne dans la table");
            flag = false;
            return ligne;
        } else {
            String pu = tableproduit.getValueAt(ligne, 3).toString();
            txtpu.setText(pu);
            String qte = tableproduit.getValueAt(ligne, 5).toString();
            txtquantite.setText(qte);
            String desi = tableproduit.getValueAt(ligne, 6).toString();
            txtdesignation.setText(desi);
            String unit =tableproduit.getValueAt(ligne, 4).toString();
            unite.setText(unit);
            flag = true;
            return ligne;

        }
    }
    public void afficher(String requette, JTable tab,String[]entete) {
        c.tableau(requette, tab, entete);
    }
    public void rechercher() {
         String[] entete = {"Reference du produit", "Code de catégorie", "Fournisseur N°", 
                "Prix unitaire","Unité", "Quantité de produit par unité", "Désignation"};
        String reqette = "select reference_produit, code_categorie,code_fournisseur,"
                + "prix_unitaire_produit,unite,quantite_par_unite,designation from produit where "
                + "designation like '" + rechercher.getText().toString() + "%';";
        afficher(reqette, tableproduit, entete);
    }
    public void modifier() {
         boolean flag = true;
        if (flag) {
            int g = tableproduit.getSelectedRow();
            int p = Integer.parseInt(tableproduit.getValueAt(g, 0).toString());
            String desi = txtdesignation.getText();
            int quantite = Integer.parseInt(txtquantite.getText().toString());
            int pu = Integer.parseInt(txtpu.getText().toString());
            int unit = Integer.parseInt(unite.getText().toString());
            String categorie = combo2.getSelectedItem().toString();
            String four = comboFour.getSelectedItem().toString();
            //String notes = txtnotes.getText().toString();
            String requete = "update produit set prix_unitaire_produit ='" + pu + "',Unite ='"+unit+"', quantite_par_unite = '" + quantite
                    + "',designation='" + desi + "'"
                    + ",code_categorie='" + categorie + "',code_fournisseur='" + four + "' where reference_produit=" + p + ";";
            Connex.update(requete);

            String reqette = "select reference_produit, code_categorie,code_fournisseur,"
                + "prix_unitaire_produit,unite,quantite_par_unite,designation from produit;";
            String[] entete = {"Reference du produit", "Code de catégorie", "Fournisseur N°", 
                "Prix unitaire","Unité", "Quantité de produit par unité", "Désignation"};
            c.tableau(reqette, tableproduit, entete);
            JOptionPane.showMessageDialog(null, "La modification a réussit !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de modification !!!");

        }
    }
    public void supprimer() {
         String reqette = "select reference_produit, code_categorie,code_fournisseur,"
                + "prix_unitaire_produit,unite,quantite_par_unite,designation from produit;";
        String[] entete = {"Reference du produit", "Code de catégorie", "Fournisseur N°", 
                "Prix unitaire","Unité", "Quantité de produit par unité", "Désignation"};
        int g = tableproduit.getSelectedRow();
        int p = Integer.parseInt(tableproduit.getValueAt(g, 0).toString());
        int reponse = JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer cet produit ?");
        if (reponse == 0) {
            String requete = "delete from produit where reference_produit=" + p + "";
            Connex.update(requete);
            c.tableau(reqette, tableproduit, entete);
            JOptionPane.showMessageDialog(null, "Suppression OK !!!");
        } else {
            JOptionPane.showMessageDialog(null, "Echec de suppression");
        }
    }
    public void ajouter() {
        String var = "insert into produit (prix_unitaire_produit ,unite, quantite_par_unite ,designation,code_categorie,code_fournisseur)"
                + "values('" + this.txtpu.getText() + "'" + ","+"'"+unite.getText()+"'"+"," + "'" + this.txtquantite.getText() + "'"
                + "," + "'" + this.txtdesignation.getText() + "'" + "," + "'" + combo2.getSelectedItem().toString()
                + "'" + "," + "'" + comboFour.getSelectedItem().toString() + "');";
        String[] entete = {"Reference du produit", "Code de catégorie", "Fournisseur N°", 
                "Prix unitaire","Unité", "Quantité de produit par unité", "Désignation"};
        String reqette = "select reference_produit, code_categorie,code_fournisseur,"
                + "prix_unitaire_produit,unite,quantite_par_unite,designation from produit;";
        System.out.println(var);
        Connex.update(var);
        c.tableau(reqette, tableproduit, entete);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bannul;
    private javax.swing.JPanel bannuler;
    private javax.swing.JButton bmodifier;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JComboBox combo2;
    private javax.swing.JComboBox comboFour;
    private javax.swing.JButton guauche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rechercher;
    private javax.swing.JTable tableproduit;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtpu;
    private javax.swing.JTextField txtquantite;
    private javax.swing.JTextField unite;
    // End of variables declaration//GEN-END:variables
}
